seed_everything: 42

# Parametry modelu MusicGenreClassifier
model:
  genre_names: 
    - Blues
    - Country
    - Electronic
    - Folk
    - International
    - Jazz
    - Latin
    - New Age
    - Pop-Rock
    - Rap
    - Reggae
    - RnB
    - Vocal   
  learning_rate: 0.001
  conv_out_channels: 64 
  conv_kernel_size: 7    
  conv_stride: 2
  conv_padding: 3

# Parametry danych MusicGenreDataModule
data:
  npy_dir: data/processed/npy_arrays
  csv_path: data/processed/labels/msd-topMAGD.csv
  batch_size: 32
  seq_len: 1024        
  num_workers: 4


# Parametry PyTorch Lightning
trainer:
  max_epochs: 400
  accelerator: auto      
  devices: 1
  log_every_n_steps: 50
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      entity: "01169653-politechnika-warszawska"
      project: "symbolic-music-genre-interpretability"
      name: "baseline_resnet18"
      log_model: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 1
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: models/
        filename: "resnet18_prototype-{epoch:02d}-{val_loss:.2f}"
        monitor: "val_loss"
        mode: "min"
        save_top_k: 1
        save_last: true
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
        min_delta: 0.00        
        patience: 10           
        mode: "min"
